name: I WAS HERE
favicon: null
layout_spectrum: 0.99903
typography_spectrum: 0.96394
title: I WAS HERE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212121'
    - '#d9e0d8'
    - '#41423a'
    - '#afafaf'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
