name: I WAS HERE
favicon: null
layout_spectrum: 0.26901
typography_spectrum: 0.58674
title: I WAS HERE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff5f0'
    - '#0097ae'
    - '#00dada'
    - '#7ecfb5'
    - '#004d4f'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
